name: multiclass_mlflow
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - requests=2.24.0
  - pip=21.3.1
  - numpy=1.23.4
  - seaborn=0.13.0
  - nltk=3.8.1
  - gunicorn
  - pip:
      - mlflow==1.14.1
      - protobuf==3.20.1
      - ktrain==0.35.1
      - textblob==0.17.1
      - pytest